DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS DOMICILIOS;
DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO VARCHAR(50) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
STATE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI VARCHAR(10) NOT NULL UNIQUE,
FECHA_REGISTRO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL,
STATE BOOLEAN DEFAULT TRUE,
FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIOS(ID)
);

CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NUM_MATRICULA VARCHAR(10) NOT NULL UNIQUE,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
STATE BOOLEAN DEFAULT TRUE
);

-- Insertar domicilios
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, CIUDAD) VALUES
('Av. Siempre Viva', '742', 'Springfield', 'Illinois'),
('Calle Falsa', '123', 'Ciudad Gótica', 'Nueva Jersey'),
('Boulevard de los Sueños', '456', 'Quahog', 'Rhode Island');

-- Insertar pasientes
INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA_REGISTRO, ID_DOMICILIO) VALUES
('Homero', 'Simpson', '12345678', CURRENT_TIMESTAMP, 1),
('Bruce', 'Wayne', '87654321', CURRENT_TIMESTAMP, 2),
('Peter', 'Griffin', '56781234', CURRENT_TIMESTAMP, 3);

-- Insertar odontologos
INSERT INTO ODONTOLOGOS (NUM_MATRICULA, NOMBRE, APELLIDO) VALUES
('OD00123', 'Ana', 'Gómez'),
('OD00124', 'Luis', 'Martínez'),
('OD00125', 'Carla', 'Rodríguez'),
('OD00126', 'Jorge', 'Fernández'),
('OD00127', 'María', 'López'),
('OD00128', 'Pedro', 'Ramírez');
