DROP TABLE IF EXISTS TURNOS;
DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS ODONTOLOGOS;
DROP TABLE IF EXISTS DOMICILIOS;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO VARCHAR(50) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
STATE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI VARCHAR(10) NOT NULL UNIQUE,
FECHA_REGISTRO TIMESTAMP NOT NULL,
ID_DOMICILIO INT NOT NULL,
STATE BOOLEAN DEFAULT TRUE,
CONSTRAINT FK_PACIENTE_DOMICILIO FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIOS(ID)
);

CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO VARCHAR(10) NOT NULL UNIQUE,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
STATE BOOLEAN DEFAULT TRUE
);

CREATE TABLE TURNOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
FECHA_CONSULTA TIMESTAMP NOT NULL,
ID_ODONTOLOGO INT NOT NULL,
ID_PACIENTE INT NOT NULL,
STATE BOOLEAN DEFAULT TRUE,
FOREIGN KEY (ID_ODONTOLOGO) REFERENCES ODONTOLOGOS(ID),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID)
);

-- Insertar domicilios
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, CIUDAD) VALUES
('Av. Siempre Viva', '742', 'Springfield', 'Illinois'),
('Calle Falsa', '123', 'Ciudad Gótica', 'Nueva Jersey'),
('Boulevard de los Sueños', '456', 'Quahog', 'Rhode Island');

-- Insertar pasientes
INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA_REGISTRO, ID_DOMICILIO) VALUES
('Homero', 'Simpson', '12345678', CURRENT_TIMESTAMP, 1),
('Bruce', 'Wayne', '87654321', CURRENT_TIMESTAMP, 2),
('Peter', 'Griffin', '56781234', CURRENT_TIMESTAMP, 3);

-- Insertar odontologos
INSERT INTO ODONTOLOGOS (CODIGO, NOMBRE, APELLIDO) VALUES
('OD00123', 'Ana', 'Gómez'),
('OD00124', 'Luis', 'Martínez'),
('OD00125', 'Carla', 'Rodríguez'),
('OD00126', 'Jorge', 'Fernández'),
('OD00127', 'María', 'López'),
('OD00128', 'Pedro', 'Ramírez');

-- Insertar turnos
INSERT INTO TURNOS (FECHA_CONSULTA, ID_ODONTOLOGO, ID_PACIENTE) VALUES
('2025-05-25', 2, 1),
('2025-06-01', 3, 2),
('2025-06-06', 1, 3),
('2025-06-20', 5, 1),
('2025-06-20', 4, 2),
('2025-06-20', 6, 3);
